### ISSUE TITLE
关于DAC输出的问题

### ISSUE THREAD

**Issue by chen03** [SHR-sky/2023-H#1]
无论输入ADC的信号是多大，DAC信号输出频率不变。并且其输出波形既不像三角波也不像正弦波
![Uploading 111.jpg…]()

**Comment by SHR-sky** [comment]
建议用串口输出fre[1]和fre[0]，观察是否成功解算出两个输入信号的频率

**Comment by SHR-sky** [comment]
并且本方案DA输出波形采用的是查表法，在FFT没有爆栈的情况下，输出的波形一定会是标准的波形。建议检查移植过程中，DMA配置是否成功。

**Comment by chen03** [comment]
好的谢谢您，我再检查一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月19日(周五) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SHR-sky/2023-H] 关于DAC输出的问题 (Issue #1)




 
并且本方案DA输出波形采用的是查表法，在FFT没有爆栈的情况下，输出的波形一定会使标准的波形。建议检查移植过程中，DMA配置是否成功。
