### ISSUE TITLE
信号频率的问题

### ISSUE THREAD

**Issue by runaway19** [SHR-sky/2023-H#2]
为什么我测到的频率飘忽不定，我是直接把fre这个数组的值显示出来，频率用的是5k的倍数

**Comment by SHR-sky** [comment]
要保证前端加法器输出的混合波形稳定。并且，main函数中只会测量一次频率，测定后不会再改变，“飘忽不定”是指每次reset后，显示的频率都不一样吗？

**Comment by runaway19** [comment]
是的

**Comment by SHR-sky** [comment]
建议首先检测加法器输出波形的稳定。如果没有问题，建议用DA将AD采到的波形直接重建，观察是否成功采样。

**Comment by runaway19** [comment]
如果我直接用示波器输入信号，那这种方法能不能将两个信号的频率分出来，如果不能，那我只是想将重叠信号的频率分出来，那要用什么方法

**Comment by SHR-sky** [comment]
首先，该方案前端需要加法器电路混合从信号发生器而来的信号，再输入混合信号到AD，不存在直接输入信号到AD。其次，关于“重叠信号频率”的问题，建议首先翻阅报告、查阅原理，以及了解频谱分析、数字正交分解的相关知识。

**Comment by runaway19** [comment]
好的，谢了
